version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: cupons-amor-db
    environment:
      POSTGRES_USER: amor
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cupons_amor_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
